//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblCategory
    {
        public tblCategory()
        {
            this.tblNews = new HashSet<tblNew>();
        }
        
        [DisplayName("ID")]
        public int iId { get; set; }

        [DisplayName("Tên")]
        [Required(ErrorMessage="Vui lòng nhập tên danh mục")]
        public string sName { get; set; }
        

        [DisplayName("Đường dẫn")]
        [Required(ErrorMessage="Vui lòng nhập đường dẫn")]
        public string link { get; set; }


        [DisplayName("Target")]
        public string taget { get; set; }


        
        [DisplayName("Slag")]
        public string slag { get; set; }
    
        public virtual ICollection<tblNew> tblNews { get; set; }
    }
}
