//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNew
    {
        public int iId { get; set; }
        public string sImage { get; set; }
        public string sTitle { get; set; }
        public string sDescription { get; set; }
        public string sContent { get; set; }
        public Nullable<int> iCategoryId { get; set; }
        public string sAuthor { get; set; }
        public Nullable<bool> bStatus { get; set; }
        public Nullable<int> iClicked { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
    }
}
